### ISSUE TITLE
Improve level function

### ISSUE THREAD

**Issue by ArmandBriere** [ArmandBriere/Archy#122]
**Is your feature request related to a problem? Please describe.**
Level returns an URL to og-vercel cloud function.
Download the image inside the cloud function and returns the base64 image to the main node
This will decrease the number of call to the og-vercel function

**Describe the solution you'd like**
- http get request `og-vercel` function from `level` function
- encode result in bas64
- Returns it to the main node
- Main node:
  - slash command -> decode and return image
  -  normal command -> detect that it is an image -> decode and return it

**Comment by CmD0** [comment]
This was resolved today with the merge to prod as far as I can tell.
