### ISSUE TITLE
Modify main node to register `/` commands

### ISSUE THREAD

**Issue by ArmandBriere** [ArmandBriere/Archy#53]
**Is your feature request related to a problem? Please describe.**
The `!` is nice but the future of discord bot is in the slash commands

**Describe the solution you'd like**
We need to modify the main node to use slash command:
- Change discord.py to pycord https://github.com/Pycord-Development/pycord
- All command should have their function
- All command function must redirect treatment to cloud function
- All command function will have description
- If a command isn't active in Firestore, send back an ephemeral message back to user

**Comment by CmD0** [comment]
I'll start looking into implementing this.

**Comment by ArmandBriere** [comment]
#114
